### ISSUE TITLE
Export xyBase

### ISSUE THREAD

**Issue by onedayitwillmake** [d3fc/d3fc-series#56]
Great library!

It would be great if `xyBase` was also exported (via the `build/d3fc` bundle), currently it's not possible to create a custom series due to this minor limitation.

**Comment by chrisprice** [comment]
Thanks Mario. We don't export the base components because we consider their
API to be an internal implementation detail. Having said that, you probably
don't need the functionality they contain to create your own series.

Most of the code contained within them is just to allow the series to be
fully customisable. If you're making a bespoke series you probably don't
need to offer that much flexibility.

The only requirements we impose on a series component in order for it to be
compatible with the library is for it to accept an xScale and a yScale.

**Comment by ColinEberhardt** [comment]
This issue was moved to d3fc/d3fc#1120
